---
dist: xenial
sudo: false

language: python
python:
- '3.6'
- 'pypy3.6-7.1.1'
cache: pip

matrix:
  fast-finish: true

env:
  - TEST_RUN='./tests/travis_python_tests'

install:
  - pip install -U .

script: "$TEST_RUN"
