---
dist: trusty
sudo: false

language: python
python:
- '3.6'
- 'pypy3.3-5.5-alpha'
cache: pip

matrix:
  fast-finish: true

env:
  - TEST_RUN='./tests/travis_python_tests'

install:
  - pip install -U .

script: "$TEST_RUN"
